first_student_name = input("Enter The First Student's  Name: ")
first_student_id = int(input("Enter The First Student's ID: "))
first_student_grade = float(input("Enter The First Student's grade: "))
print("\n")
second_student_name = input("Enter The Second Student's  Name: ")
second_student_id = int(input("Enter The Second Student's ID: "))
second_student_grade = float(input("Enter The Second Student's grade: "))
print("\n")
print('informat for  staudents and their "Math" grades')
print(first_student_name,'(ID' , first_student_id,')',"got grade :" , first_student_grade)
print(second_student_name,'(ID' , second_student_id,')',"got grade :" , second_student_grade)
sum = ((first_student_grade + second_student_grade) / 2)
print("AVerage math grade is", sum)
